// CART
export const ADD_PRODUCT_TO_BASK = 'ADD_PRODUCT_TO_BASK';
export const CART_CHANGE_LIST = 'CART_CHANGE_LIST';
export const FAVOURITES_LIST_CHANGE = 'FAVOURITES_LIST_CHANGE';

// SNACKBAR
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';
export const SNACKBAR_OPEN = 'SNACKBAR_OPEN';

// Products List
export const PRODUCTS_LIST_FETCH_ACTION = 'PRODUCTS_LIST_FETCH_ACTION';
export const PRODUCT_CREATE_ACTION = 'PRODUCT_CREATE_ACTION';
export const PRODUCT_DELETE_ACTION = 'PRODUCT_DELETE_ACTION';
export const PRODUCT_RECOMMENDATION = 'PRODUCT_RECOMMENDATION';
export const PRODUCT_RECOMMENDATION_AUTHOR = 'PRODUCT_RECOMMENDATION_AUTHOR';

// ADS
export const USER_ADS_LIST_FETCH = 'USER_ADS_LIST_FETCH';
export const ORDERS_DETAIL_FETCH_ACTION = 'ORDERS_DETAIL_FETCH_ACTION';

// Visitors
export const VISITORS_FETCH_ACTION = 'VISITORS_FETCH_ACTION';

// Countries
export const COUNTRIES_LIST_FETCH_ACTION = 'COUNTRIES_LIST_FETCH_ACTION';
export const CITIES_LIST_FETCH_ACTION = 'CITIES_LIST_FETCH_ACTION';
export const STATES_LIST_FETCH_ACTION = 'STATES_LIST_FETCH_ACTION';

// Cashbacks
export const CASHBACKS_LIST_FETCH_ACTION = 'CASHBACKS_LIST_FETCH_ACTION';

// Fetch by categories
export const FETCH_BY_CATEGORY = 'FETCH_BY_CATEGORY';
export const TAGS_LIST_FETCH_ACTION = 'TAGS_LIST_FETCH_ACTION';

// Auth
export const USER_AUTH_SING_IN = 'USER_AUTH';
export const USER_SETTINGS = 'USER_SETTINGS';
export const USER_AUTH = 'USER_AUTH';
export const USER_AUTH_SING_UP = 'USER_AUTH_SING_UP';
export const USER_AUTH_SING_UP_COMPLETE = 'USER_AUTH_SING_UP_COMPLETE';
export const USER_DELETE = 'USER_DELETE';

// Dialog
export const DIALOG_OPEN = 'DIALOG_OPEN';
export const DIALOG_CLOSE = 'DIALOG_CLOSE';

// Error dialog
export const ERROR_DIALOG_OPEN = 'ERROR_DIALOG_OPEN';
export const ERROR_DIALOG_CLOSE = 'ERROR_DIALOG_CLOSE';

// Messages
export const MESSAGES_LIST_FETCH = 'MESSAGES_LIST_FETCH';

// User details
export const USER_DETAILS_FETCH = 'USER_DETAILS_FETCH';
export const USER_PRODUCTS_FETCH = 'USER_PRODUCTS_FETCH';
export const CHAT_CREATE = 'CHAT_CREATE';

// Followers
export const FOLLOWERS_LIST_FETCH = 'FOLLOWERS_LIST_FETCH';
export const FOLLOWINGS_LIST_FETCH = 'FOLLOWINGS_LIST_FETCH';
export const FOLLOW_CREATE = 'FOLLOW_CREATE';

// Favourites
export const USER_FAVOURITES_LIST_FETCH = 'USER_FAVOURITES_LIST_FETCH'
